version: '3.8'
services:
  catalog:
    build: ./catalog
    ports:
      - "5000:5000"
  orders:
    build: ./orders
    ports:
      - "5001:5001"
  users:
    build: ./users
    ports:
      - "5002:5002"
